// Bank soal ujian Bahasa Sunda.
// Setiap soal: { topik, soal, pilihan: [...], jawaban: index, bacaan?: "...", catatan?: "penjelasan" }
// "jawaban" = index pilihan yang benar (mulai dari 0).

const BACAAN_KELAS2 = `Isuk-isuk Wawan jeung Nina indit ka sakola babarengan. Di jalan maranéhna papanggih jeung Pa Guru. Barang nepi ka sakola, Asép kakara datang sabab hudang kabeurangan.`;

export const SOAL_KELAS2 = [
  {
    topik: "Bacaan",
    bacaan: BACAAN_KELAS2,
    soal: "Saha waé tokoh anu aya dina bacaan di luhur?",
    pilihan: ["Wawan, Nina, Pa Guru, jeung Asép", "Ujang jeung Néng", "Si Kabayan", "Bapa jeung Ibu"],
    jawaban: 0,
    catatan: "Tokoh dina bacaan nyaéta Wawan, Nina, Pa Guru, jeung Asép.",
  },
  {
    topik: "Bacaan",
    bacaan: BACAAN_KELAS2,
    soal: "Saha anu indit ka sakola babarengan?",
    pilihan: ["Wawan jeung Nina", "Asép jeung Pa Guru", "Nina hungkul", "Pa Guru jeung Wawan"],
    jawaban: 0,
    catatan: "Wawan jeung Nina indit ka sakola babarengan.",
  },
  {
    topik: "Bacaan",
    bacaan: BACAAN_KELAS2,
    soal: "Saha anu datang telat (kabeurangan) ka sakola?",
    pilihan: ["Asép", "Wawan", "Nina", "Pa Guru"],
    jawaban: 0,
    catatan: "Asép datang telat sabab hudang kabeurangan.",
  },
  {
    topik: "Gotong Royong",
    soal: "Naon mangpaatna gotong royong téh?",
    pilihan: ["Pagawéan jadi énténg sarta gancang réngsé", "Pagawéan jadi beurat", "Babaturan jadi paséa", "Imah jadi kotor"],
    jawaban: 0,
    catatan: "Ku gotong royong, pagawéan jadi énténg sarta gancang réngsé.",
  },
  {
    topik: "Bacaan",
    bacaan: BACAAN_KELAS2,
    soal: "Iraha Wawan jeung Nina indit ka sakola?",
    pilihan: ["Isuk-isuk", "Peuting", "Soré", "Tengah poé"],
    jawaban: 0,
    catatan: "Maranéhna indit isuk-isuk.",
  },
  {
    topik: "Undak Usuk Basa",
    soal: "Kecap hormat (lemes) tina 'dahar' pikeun kolot nyaéta…",
    pilihan: ["tuang", "nyatu", "lebok", "hakan"],
    jawaban: 0,
    catatan: "Kecap lemes tina 'dahar' nyaéta 'tuang'.",
  },
  {
    topik: "Sasatoan",
    soal: "Anak hayam dina basa Sunda disebut…",
    pilihan: ["ciak", "meri", "belo", "kirik"],
    jawaban: 0,
    catatan: "Anak hayam = ciak. (meri = anak bébék, belo = anak kuda, kirik = anak anjing)",
  },
  {
    topik: "Sasatoan",
    soal: "Anak anjing dina basa Sunda disebut…",
    pilihan: ["kirik", "ciak", "méong", "burayak"],
    jawaban: 0,
    catatan: "Anak anjing = kirik.",
  },
  {
    topik: "Parab Sasatoan",
    soal: "Munding (kebo) biasana diparaban ku…",
    pilihan: ["jukut", "lauk", "daging", "gabah"],
    jawaban: 0,
    catatan: "Parab munding nyaéta jukut (rumput).",
  },
  {
    topik: "Kalimah Uleman",
    soal: "Lengkepan kalimah ieu: '___ urang diajar babarengan!'",
    pilihan: ["Hayu", "Ulah", "Tong", "Henteu"],
    jawaban: 0,
    catatan: "Kecap uleman/ajakan nu merenah nyaéta 'Hayu'.",
  },
  {
    topik: "Kalimah Sopan Santun",
    soal: "Mun rék nginjeum pulpén babaturan, urang kudu ngomong…",
    pilihan: ["“Punten, abdi badé nginjeum pulpénna.”", "“Béré ka aing!”", "“Pasihan!”", "“Geura bikeun!”"],
    jawaban: 0,
    catatan: "Kalimah sopan ngagunakeun kecap 'punten' jeung 'abdi'.",
  },
  {
    topik: "Kagiatan Masarakat",
    soal: "Kagiatan beberesih lingkungan babarengan di kampung disebut…",
    pilihan: ["gotong royong / kerja bakti", "piknik", "tunduh", "ulin"],
    jawaban: 0,
    catatan: "Beberesih babarengan disebut gotong royong atawa kerja bakti.",
  },
  {
    topik: "Waditra Sunda",
    soal: "Suling téh waditra (alat musik) Sunda anu dimaénkeun ku cara…",
    pilihan: ["ditiup", "dipetik", "dipukul", "digésék"],
    jawaban: 0,
    catatan: "Suling dimaénkeun ku cara ditiup.",
  },
  {
    topik: "Éjahan",
    soal: "Kalimah anu bener cara nulisna nyaéta…",
    pilihan: ["Abdi sakola di Bandung.", "abdi sakola di bandung", "Abdi Sakola Di Bandung.", "abdi Sakola di Bandung"],
    jawaban: 0,
    catatan: "Awal kalimah jeung ngaran tempat ditulis ku aksara gedé (kapital).",
  },
  {
    topik: "Kalimah Ajakan",
    soal: "Lengkepan: '_____ urang piknik ka kebon binatang!'",
    pilihan: ["Hayu", "Ulah", "Henteu", "Tong"],
    jawaban: 0,
    catatan: "Kecap ajakan nu merenah nyaéta 'Hayu'.",
  },
  {
    topik: "Gambar Kagiatan",
    soal: "Aya budak nu nyekel sapu keur beberesih buruan. Kalimah nu merenah nyaéta…",
    pilihan: ["Budak keur nyapu buruan.", "Budak keur saré.", "Budak keur dahar.", "Budak keur ulin bal."],
    jawaban: 0,
    catatan: "Nyekel sapu bari beberesih hartina keur nyapu.",
  },
  {
    topik: "Kabersihan Lingkungan",
    soal: "Sangkan lingkungan beresih, urang kudu miceun runtah ka…",
    pilihan: ["tempat runtah (tong sampah)", "walungan", "jalan", "kolong méja"],
    jawaban: 0,
    catatan: "Runtah kudu dipiceun ka tempat runtah.",
  },
  {
    topik: "Posyandu",
    soal: "Indung mawa adi nu masih orok pikeun ditimbang jeung diimunisasi. Tempatna disebut…",
    pilihan: ["Posyandu", "Pasar", "Sakola", "Masjid"],
    jawaban: 0,
    catatan: "Tempat nimbang jeung imunisasi orok nyaéta Posyandu.",
  },
  {
    topik: "Tatakrama Basa",
    soal: "Mun rék ka cai (kamar mandi) di kelas, urang ménta idin ka guru ku cara…",
    pilihan: ["“Punten Bu, abdi badé ka pengker.”", "“Bu, kuring ka cai!”", "Langsung kaluar wéh", "Cicing baé"],
    jawaban: 0,
    catatan: "Ménta idin ku basa lemes: 'Punten Bu, abdi badé ka pengker.'",
  },
  {
    topik: "Kasenian Sunda",
    soal: "Ieu di handap conto pupuh anu sok ditembangkeun, nyaéta…",
    pilihan: ["Pupuh Pucung", "Lagu Balonku", "Lagu Pelangi", "Lagu Cicak"],
    jawaban: 0,
    catatan: "Pucung mangrupa salah sahiji pupuh dina kasenian Sunda.",
  },
  {
    topik: "Perlengkapan Sakola",
    soal: "Barang anu dibawa ka sakola pikeun nulis nyaéta…",
    pilihan: ["pulpén jeung buku", "péso", "piring", "sapu"],
    jawaban: 0,
    catatan: "Pikeun nulis di sakola urang mawa pulpén jeung buku.",
  },
  {
    topik: "Kagiatan di Sakola",
    soal: "Kagiatan anu biasa dilakukeun di sakola nyaéta…",
    pilihan: ["diajar jeung maca buku", "masak", "saré", "ngarit jukut"],
    jawaban: 0,
    catatan: "Di sakola urang diajar jeung maca buku.",
  },
  {
    topik: "Usum",
    soal: "Di Indonésia aya dua usum, nyaéta usum…",
    pilihan: ["hujan jeung halodo (kemarau)", "salju jeung gugur", "semi jeung salju", "tiris jeung salju"],
    jawaban: 0,
    catatan: "Indonésia boga dua usum: usum hujan jeung usum halodo.",
  },
  {
    topik: "Kajadian Alam",
    soal: "Lamun usum hujan turun terus-terusan, sok aya kajadian…",
    pilihan: ["caah (banjir)", "halodo", "gunung bitu", "lini"],
    jawaban: 0,
    catatan: "Hujan gedé bisa nyababkeun caah (banjir).",
  },
  {
    topik: "Cuaca",
    soal: "Dina usum halodo (kemarau), kaayaan cuacana…",
    pilihan: ["panas tur garing", "tiis jeung hujan", "loba salju", "loba angin topan"],
    jawaban: 0,
    catatan: "Usum halodo cuacana panas sarta taneuh jadi garing.",
  },
  {
    topik: "Undak Usuk Basa",
    soal: "Kecap hormat (lemes) tina 'leungeun' nyaéta…",
    pilihan: ["panangan", "suku", "sirah", "irung"],
    jawaban: 0,
    catatan: "Kecap lemes tina 'leungeun' nyaéta 'panangan'.",
  },
  {
    topik: "Waditra Sunda",
    soal: "Kendang téh waditra Sunda anu dimaénkeun ku cara…",
    pilihan: ["ditepak (dipukul ku leungeun)", "ditiup", "dipetik", "digésék"],
    jawaban: 0,
    catatan: "Kendang dimaénkeun ku cara ditepak/dipukul.",
  },
  {
    topik: "Waditra Sunda",
    soal: "Angklung téh waditra Sunda anu dimaénkeun ku cara…",
    pilihan: ["digoyangkeun (dikocok)", "dipetik", "ditiup", "digésék"],
    jawaban: 0,
    catatan: "Angklung dimaénkeun ku cara digoyangkeun.",
  },
  {
    topik: "Sasatoan",
    soal: "Anak bébék dina basa Sunda disebut…",
    pilihan: ["meri", "ciak", "kirik", "belo"],
    jawaban: 0,
    catatan: "Anak bébék = meri.",
  },
  {
    topik: "Parab Sasatoan",
    soal: "Ucing biasana resep dahar (parabna)…",
    pilihan: ["lauk", "jukut", "paré", "daun"],
    jawaban: 0,
    catatan: "Parab ucing nyaéta lauk.",
  },
  {
    topik: "Wilangan",
    soal: "Angka '3' dina basa Sunda nyaéta…",
    pilihan: ["tilu", "dua", "opat", "lima"],
    jawaban: 0,
    catatan: "3 = tilu, 2 = dua, 4 = opat, 5 = lima.",
  },
  {
    topik: "Warna",
    soal: "Warna 'bodas' dina basa Indonésia hartina…",
    pilihan: ["putih", "hitam", "merah", "biru"],
    jawaban: 0,
    catatan: "Bodas = putih.",
  },
  {
    topik: "Kulawarga",
    soal: "Lanceuk awéwé (kakak perempuan) urang disebut…",
    pilihan: ["teteh (ceuceu)", "adi", "ema", "bapa"],
    jawaban: 0,
    catatan: "Kakak perempuan = teteh/ceuceu.",
  },
  {
    topik: "Anggota Awak",
    soal: "Panon (mata) dipaké pikeun…",
    pilihan: ["ningali (ngempét)", "ngadéngé", "ngambeu", "ngrasa amis"],
    jawaban: 0,
    catatan: "Panon dipaké pikeun ningali (melihat).",
  },
  {
    topik: "Kadaharan",
    soal: "Sangu (nasi) asalna tina…",
    pilihan: ["paré (beas)", "jagong", "sampeu", "kentang"],
    jawaban: 0,
    catatan: "Sangu dijieun tina beas, beas asalna tina paré.",
  },
  {
    topik: "Tatakrama Basa",
    soal: "Mun hayang ménta hampura ka batur, urang ngomong…",
    pilihan: ["“Hapunten…”", "“Haturnuhun”", "“Wilujeng”", "“Sami-sami”"],
    jawaban: 0,
    catatan: "Ménta hampura: 'Hapunten'. Haturnuhun = terima kasih.",
  },
  {
    topik: "Kabersihan Lingkungan",
    soal: "Méméh saré, sangkan huntu beresih urang kudu nyikat huntu maké…",
    pilihan: ["odol jeung sikat huntu", "sabun mandi", "sapu", "lap meja"],
    jawaban: 0,
    catatan: "Nyikat huntu maké odol jeung sikat huntu.",
  },
  {
    topik: "Kasenian Sunda",
    soal: "Tari Jaipong téh kasenian anu asalna ti daérah…",
    pilihan: ["Jawa Barat (Sunda)", "Bali", "Papua", "Aceh"],
    jawaban: 0,
    catatan: "Jaipong mangrupa tarian has Jawa Barat (Sunda).",
  },
  {
    topik: "Wanci (Waktu)",
    soal: "Sanggeus wanci isuk, datang wanci…",
    pilihan: ["beurang", "peuting", "subuh", "sareupna"],
    jawaban: 0,
    catatan: "Urutanana: isuk → beurang → soré → peuting.",
  },
  {
    topik: "Tutuwuhan",
    soal: "Tangkal cau (pohon pisang) ngahasilkeun buah…",
    pilihan: ["cau", "kalapa", "paré", "jambu"],
    jawaban: 0,
    catatan: "Tangkal cau ngahasilkeun cau (pisang).",
  },
  {
    topik: "Gambar — Sasatoan",
    gambar: "🐘",
    soal: "Sato dina gambar ieu, dina basa Sunda disebut…",
    pilihan: ["gajah", "maung", "monyét", "ucing"],
    jawaban: 0,
    catatan: "Sato dina gambar nyaéta gajah.",
  },
  {
    topik: "Gambar — Sasatoan",
    gambar: "🐟",
    soal: "Sato dina gambar ieu, dina basa Sunda disebut…",
    pilihan: ["lauk", "manuk", "embé", "kuda"],
    jawaban: 0,
    catatan: "Sato dina gambar nyaéta lauk (ikan).",
  },
  {
    topik: "Gambar — Waditra",
    gambar: "🥁",
    soal: "Waditra (alat musik) dina gambar ieu dimaénkeun ku cara…",
    pilihan: ["ditepak (dipukul)", "ditiup", "dipetik", "digésék"],
    jawaban: 0,
    catatan: "Kendang dina gambar dimaénkeun ku cara ditepak/dipukul.",
  },
  {
    topik: "Gambar — Waditra",
    gambar: "🪈",
    soal: "Waditra dina gambar ieu (suling) dimaénkeun ku cara…",
    pilihan: ["ditiup", "ditepak", "dipetik", "digésék"],
    jawaban: 0,
    catatan: "Suling dimaénkeun ku cara ditiup.",
  },
  {
    topik: "Gambar — Cuaca",
    gambar: "🌧️☂️",
    soal: "Tingali gambar ieu. Kaayaan kieu lumangsung dina usum…",
    pilihan: ["hujan", "halodo", "salju", "panas"],
    jawaban: 0,
    catatan: "Hujan jeung payung nuduhkeun usum hujan.",
  },
  {
    topik: "Gambar — Cuaca",
    gambar: "☀️",
    soal: "Tingali gambar ieu. Cuacana keur…",
    pilihan: ["panas (halodo)", "hujan", "tiris jeung salju", "angin topan"],
    jawaban: 0,
    catatan: "Panonpoé caang nuduhkeun cuaca panas (halodo).",
  },
  {
    topik: "Gambar — Kagiatan",
    gambar: "🧹",
    soal: "Barudak nyekel pakakas dina gambar ieu keur…",
    pilihan: ["nyapu", "dahar", "saré", "ulin bal"],
    jawaban: 0,
    catatan: "Sapu dipaké pikeun nyapu.",
  },
  {
    topik: "Gambar — Buah",
    gambar: "🍌",
    soal: "Buah dina gambar ieu, dina basa Sunda disebut…",
    pilihan: ["cau", "jeruk", "kalapa", "jambu"],
    jawaban: 0,
    catatan: "Buah dina gambar nyaéta cau (pisang).",
  },
  {
    topik: "Undak Usuk Basa",
    soal: "Kecap hormat (lemes) tina 'sirah' (kepala) nyaéta…",
    pilihan: ["mastaka", "suku", "leungeun", "ceuli"],
    jawaban: 0,
    catatan: "Kecap lemes tina 'sirah' nyaéta 'mastaka'.",
  },
  {
    topik: "Undak Usuk Basa",
    soal: "Kecap hormat (lemes) tina 'huntu' (gigi) nyaéta…",
    pilihan: ["waos", "ceuli", "suku", "biwir"],
    jawaban: 0,
    catatan: "Kecap lemes tina 'huntu' nyaéta 'waos'.",
  },
  {
    topik: "Undak Usuk Basa",
    soal: "Kecap hormat (lemes) tina 'nyarita' (bicara) nyaéta…",
    pilihan: ["nyarios", "ngagorowok", "ceurik", "seuri"],
    jawaban: 0,
    catatan: "Kecap lemes tina 'nyarita' nyaéta 'nyarios'.",
  },
  {
    topik: "Undak Usuk Basa",
    soal: "Kecap hormat (lemes) tina 'balik' (pulang) nyaéta…",
    pilihan: ["mulih", "indit", "lumpat", "diuk"],
    jawaban: 0,
    catatan: "Kecap lemes tina 'balik' nyaéta 'mulih'.",
  },
  {
    topik: "Undak Usuk Basa",
    soal: "Kecap hormat (lemes) tina 'diuk' (duduk) nyaéta…",
    pilihan: ["calik", "nangtung", "leumpang", "lumpat"],
    jawaban: 0,
    catatan: "Kecap lemes tina 'diuk' nyaéta 'calik'.",
  },
  {
    topik: "Sora Sasatoan",
    soal: "Sora anjing (sasauran anjing) disebut…",
    pilihan: ["ngagogog", "ngéong", "kongkorongok", "ngagaur"],
    jawaban: 0,
    catatan: "Anjing sasada ngagogog; ucing ngéong.",
  },
  {
    topik: "Sora Sasatoan",
    soal: "Hayam jago (jantan) isuk-isuk sok disada…",
    pilihan: ["kongkorongok", "ngéong", "ngagogog", "ngagaur"],
    jawaban: 0,
    catatan: "Hayam jago disada 'kongkorongok' isuk-isuk.",
  },
  {
    topik: "Sasatoan",
    soal: "Sato leutik nu sok hiber, nyokot madu, sarta nyeureudna nyeri nyaéta…",
    pilihan: ["nyiruan (lebah)", "reungit", "lalay", "kukupu"],
    jawaban: 0,
    catatan: "Nyiruan = lebah, sok nyieun madu.",
  },
  {
    topik: "Sasatoan",
    soal: "Sato nu hiber peuting sarta sok ngagantung tibalik nyaéta…",
    pilihan: ["lalay (kelelawar)", "manuk", "hayam", "nyiruan"],
    jawaban: 0,
    catatan: "Lalay (kelelawar) aktif peuting sarta ngagantung tibalik.",
  },
  {
    topik: "Sasatoan",
    soal: "Sato leutik nu sok ngarayap di tembok bari néwak reungit nyaéta…",
    pilihan: ["cakcak (cicak)", "ucing", "lauk", "embé"],
    jawaban: 0,
    catatan: "Cakcak (cicak) sok ngarayap di tembok néwak reungit.",
  },
  {
    topik: "Kosakata",
    soal: "'Sireum' dina basa Indonésia hartina…",
    pilihan: ["semut", "lalat", "nyamuk", "lebah"],
    jawaban: 0,
    catatan: "Sireum = semut.",
  },
  {
    topik: "Kosakata",
    soal: "'Kukupu' dina basa Indonésia hartina…",
    pilihan: ["kupu-kupu", "capung", "lebah", "semut"],
    jawaban: 0,
    catatan: "Kukupu = kupu-kupu.",
  },
  {
    topik: "Kosakata",
    soal: "'Gedang' dina basa Indonésia hartina…",
    pilihan: ["pepaya", "mangga", "nangka", "jambu"],
    jawaban: 0,
    catatan: "Gedang = pepaya.",
  },
  {
    topik: "Kosakata",
    soal: "'Sampeu' dina basa Indonésia hartina…",
    pilihan: ["singkong", "kentang", "talas", "ubi jalar"],
    jawaban: 0,
    catatan: "Sampeu = singkong.",
  },
  {
    topik: "Kulawarga",
    soal: "'Adi' dina basa Indonésia hartina…",
    pilihan: ["adik", "kakak", "ayah", "ibu"],
    jawaban: 0,
    catatan: "Adi = adik.",
  },
  {
    topik: "Kulawarga",
    soal: "'Bapa' dina basa Indonésia hartina…",
    pilihan: ["ayah", "ibu", "kakek", "paman"],
    jawaban: 0,
    catatan: "Bapa = ayah.",
  },
  {
    topik: "Kulawarga",
    soal: "'Aki' dina basa Indonésia hartina…",
    pilihan: ["kakek", "nenek", "paman", "bibi"],
    jawaban: 0,
    catatan: "Aki = kakek.",
  },
  {
    topik: "Kulawarga",
    soal: "'Nini' dina basa Indonésia hartina…",
    pilihan: ["nenek", "kakek", "ibu", "bibi"],
    jawaban: 0,
    catatan: "Nini = nenek.",
  },
  {
    topik: "Panca Indra",
    soal: "Irung (hidung) dipaké pikeun…",
    pilihan: ["ngambeu (mencium bau)", "ningali", "ngadéngé", "leumpang"],
    jawaban: 0,
    catatan: "Irung dipaké pikeun ngambeu (mencium bau).",
  },
  {
    topik: "Panca Indra",
    soal: "Ceuli (telinga) dipaké pikeun…",
    pilihan: ["ngadéngé", "ningali", "ngambeu", "nyabak"],
    jawaban: 0,
    catatan: "Ceuli dipaké pikeun ngadéngé (mendengar).",
  },
  {
    topik: "Panca Indra",
    soal: "Suku (kaki) dipaké pikeun…",
    pilihan: ["leumpang", "ningali", "ngadéngé", "ngambeu"],
    jawaban: 0,
    catatan: "Suku dipaké pikeun leumpang (berjalan).",
  },
  {
    topik: "Panca Indra",
    soal: "Létah (lidah) dipaké pikeun…",
    pilihan: ["ngasaan rasa", "ningali", "ngadéngé", "leumpang"],
    jawaban: 0,
    catatan: "Létah dipaké pikeun ngasaan rasa (mengecap).",
  },
  {
    topik: "Wilangan",
    soal: "Angka '6' dina basa Sunda nyaéta…",
    pilihan: ["genep", "lima", "tujuh", "dalapan"],
    jawaban: 0,
    catatan: "6 = genep.",
  },
  {
    topik: "Wilangan",
    soal: "Angka '10' dina basa Sunda nyaéta…",
    pilihan: ["sapuluh", "salapan", "dalapan", "sabelas"],
    jawaban: 0,
    catatan: "10 = sapuluh.",
  },
  {
    topik: "Warna",
    soal: "Warna 'biru' dina basa Sunda nyaéta…",
    pilihan: ["bulao", "héjo", "konéng", "beureum"],
    jawaban: 0,
    catatan: "Biru = bulao.",
  },
  {
    topik: "Poé (Hari)",
    soal: "Poé sanggeus poé Senén nyaéta poé…",
    pilihan: ["Salasa", "Minggu", "Saptu", "Juma'ah"],
    jawaban: 0,
    catatan: "Urutan: Senén, Salasa, Rebo, Kemis, Juma'ah, Saptu, Minggu.",
  },
  {
    topik: "Tatakrama Basa",
    soal: "Sanggeus dibéré atawa dibantu ku batur, urang ngucapkeun…",
    pilihan: ["“Haturnuhun”", "“Punten”", "“Hampura”", "“Wilujeng”"],
    jawaban: 0,
    catatan: "Haturnuhun = terima kasih.",
  },
  {
    topik: "Tatakrama Basa",
    soal: "Mun papanggih jeung batur dina wanci isuk, urang ngucapkeun…",
    pilihan: ["“Wilujeng énjing”", "“Wilujeng wengi”", "“Wilujeng sonten”", "“Wilujeng tepang”"],
    jawaban: 0,
    catatan: "Wilujeng énjing = selamat pagi.",
  },
  {
    topik: "Kabersihan",
    soal: "Saméméh dahar, sangkan séhat urang kudu ngumbah…",
    pilihan: ["leungeun (cuci tangan)", "buku", "méja", "korsi"],
    jawaban: 0,
    catatan: "Saméméh dahar kudu ngumbah leungeun ngarah teu gering.",
  },
  {
    topik: "Kajadian Alam",
    soal: "Panonpoé medal (terbit) di beulah…",
    pilihan: ["wétan (timur)", "kulon", "kalér", "kidul"],
    jawaban: 0,
    catatan: "Panonpoé medal di wétan (timur).",
  },
  {
    topik: "Kagiatan di Sakola",
    soal: "Saméméh ngamimitian diajar di kelas, urang biasana…",
    pilihan: ["ngado'a (berdoa)", "ulin bal", "saré", "dahar"],
    jawaban: 0,
    catatan: "Saméméh diajar urang ngado'a heula.",
  },
];

export const SOAL_KELAS3 = [
  {
    topik: "Dongéng / Legénda",
    soal: "Dongéng asal-usul Gunung Tangkuban Parahu nyaéta…",
    pilihan: ["Sangkuriang", "Lutung Kasarung", "Malin Kundang", "Si Kabayan"],
    jawaban: 0,
    catatan: "Tangkuban Parahu asalna tina legénda Sangkuriang.",
  },
  {
    topik: "Kosakata",
    soal: "Meuli barang di warung kudu maké…",
    pilihan: ["artos (duit)", "batu", "daun", "beas"],
    jawaban: 0,
    catatan: "Meuli barang maké artos (duit).",
  },
  {
    topik: "Undak Usuk Basa",
    soal: "Kecap hormat (lemes) tina 'saré' nyaéta…",
    pilihan: ["kulem", "héés", "mondok", "tunduh"],
    jawaban: 0,
    catatan: "Kecap lemes tina 'saré' nyaéta 'kulem'.",
  },
  {
    topik: "Undak Usuk Basa",
    soal: "Kecap hormat (lemes) tina 'indit' nyaéta…",
    pilihan: ["angkat", "miang", "leumpang", "lumpat"],
    jawaban: 0,
    catatan: "Kecap lemes tina 'indit' nyaéta 'angkat'.",
  },
  {
    topik: "Undak Usuk Basa",
    soal: "Kecap lemes tina 'imah' (imah batur) nyaéta…",
    pilihan: ["bumi", "saung", "gubug", "rorompok"],
    jawaban: 0,
    catatan: "Imah batur = bumi; imah sorangan = rorompok.",
  },
  {
    topik: "Sasatoan",
    soal: "Anak embé dina basa Sunda disebut…",
    pilihan: ["cémé", "kirik", "belo", "meri"],
    jawaban: 0,
    catatan: "Anak embé = cémé.",
  },
  {
    topik: "Sasatoan",
    soal: "Anak lauk (ikan) dina basa Sunda disebut…",
    pilihan: ["burayak", "ciak", "meri", "belo"],
    jawaban: 0,
    catatan: "Anak lauk = burayak.",
  },
  {
    topik: "Sasatoan",
    soal: "Anak kuda dina basa Sunda disebut…",
    pilihan: ["belo", "kirik", "cémé", "ciak"],
    jawaban: 0,
    catatan: "Anak kuda = belo.",
  },
  {
    topik: "Sasatoan",
    soal: "Sato anu awakna pangbadagna di darat nyaéta…",
    pilihan: ["gajah", "ucing", "hayam", "lauk"],
    jawaban: 0,
    catatan: "Gajah mangrupa sato darat panggedéna.",
  },
  {
    topik: "Pupuh",
    soal: "Ieu di handap kaasup pupuh, iwal ti…",
    pilihan: ["Balonku", "Pucung", "Sinom", "Asmarandana"],
    jawaban: 0,
    catatan: "Balonku lain pupuh; Pucung, Sinom, jeung Asmarandana mangrupa pupuh.",
  },
  {
    topik: "Cuaca",
    soal: "Kaayaan cuaca anu tiis sarta loba cai turun ti langit disebut…",
    pilihan: ["hujan", "halodo", "panas", "garing"],
    jawaban: 0,
    catatan: "Cai turun ti langit hartina hujan.",
  },
  {
    topik: "Usum",
    soal: "Usum halodo disebut ogé usum…",
    pilihan: ["panas (garing)", "hujan", "salju", "tiris"],
    jawaban: 0,
    catatan: "Usum halodo = usum panas/kemarau, hawana panas tur garing.",
  },
  {
    topik: "Pagawéan",
    soal: "Jalma anu pagawéanana ngajar di sakola disebut…",
    pilihan: ["guru", "dokter", "patani", "supir"],
    jawaban: 0,
    catatan: "Nu ngajar di sakola nyaéta guru.",
  },
  {
    topik: "Pagawéan",
    soal: "Jalma anu ngubaran nu gering disebut…",
    pilihan: ["dokter", "guru", "tukang pos", "patani"],
    jawaban: 0,
    catatan: "Nu ngubaran nu gering nyaéta dokter.",
  },
  {
    topik: "Pagawéan",
    soal: "Jalma anu melak paré di sawah disebut…",
    pilihan: ["patani", "nelayan", "dokter", "guru"],
    jawaban: 0,
    catatan: "Nu melak paré di sawah nyaéta patani.",
  },
  {
    topik: "Kosakata",
    soal: "Bungbuahan anu jerona beureum sarta loba sikina leutik nyaéta…",
    pilihan: ["jambu batu", "pelem (mangga)", "cau (cau)", "jeruk"],
    jawaban: 0,
    catatan: "Jambu batu jerona beureum sarta loba siki leutikna.",
  },
  {
    topik: "Hirup Séhat",
    soal: "Sangkan awak séhat, urang kudu remen…",
    pilihan: ["dahar sayur jeung bungbuahan", "ulin di jalan", "teu mandi", "maén HP sapeuting"],
    jawaban: 0,
    catatan: "Dahar sayur jeung buah ngajadikeun awak séhat.",
  },
  {
    topik: "Kabersihan",
    soal: "Sabada dahar, piring anu kotor kudu…",
    pilihan: ["dikumbah (dicuci)", "dipiceun", "diantep", "disumputkeun"],
    jawaban: 0,
    catatan: "Piring kotor kudu dikumbah sangkan beresih.",
  },
  {
    topik: "Kalimah Panyarék",
    soal: "Kecap anu nuduhkeun larangan (panyarék) nyaéta…",
    pilihan: ["ulah", "hayu", "sok", "mangga"],
    jawaban: 0,
    catatan: "'Ulah' hartina larangan, contona 'Ulah miceun runtah sambarangan'.",
  },
  {
    topik: "Kalimah Ajakan",
    soal: "Kecap pikeun ngajak babaturan nyaéta…",
    pilihan: ["hayu", "ulah", "henteu", "tong"],
    jawaban: 0,
    catatan: "Kecap ajakan nyaéta 'hayu'.",
  },
  {
    topik: "Tatakrama",
    soal: "Mun papanggih jeung guru di jalan, urang kudu…",
    pilihan: ["uluk salam tur sopan", "nyumput", "teu malire", "ngabuburak"],
    jawaban: 0,
    catatan: "Ka guru kudu uluk salam tur sopan.",
  },
  {
    topik: "Wilangan",
    soal: "Wilangan (angka) '7' dina basa Sunda nyaéta…",
    pilihan: ["tujuh", "genep", "dalapan", "salapan"],
    jawaban: 0,
    catatan: "7 = tujuh, 6 = genep, 8 = dalapan, 9 = salapan.",
  },
  {
    topik: "Warna",
    soal: "Warna 'héjo' dina basa Indonésia hartina…",
    pilihan: ["hijau", "merah", "kuning", "biru"],
    jawaban: 0,
    catatan: "Héjo = hijau.",
  },
  {
    topik: "Anggota Awak",
    soal: "'Panangan' dina basa lemes hartina…",
    pilihan: ["tangan (leungeun)", "suku", "panon", "sirah"],
    jawaban: 0,
    catatan: "Panangan = leungeun (tangan) dina basa lemes.",
  },
  {
    topik: "Dongéng",
    soal: "Carita ngeunaan sato anu bisa ngomong saperti jalma disebut…",
    pilihan: ["dongéng sasatoan (fabel)", "berita", "biografi", "iklan"],
    jawaban: 0,
    catatan: "Carita sato nu bisa ngomong disebut dongéng sasatoan atawa fabel.",
  },
  {
    topik: "Undak Usuk Basa",
    soal: "Kecap hormat (lemes) tina 'dahar' nyaéta…",
    pilihan: ["tuang", "lebok", "hakan", "nyatu"],
    jawaban: 0,
    catatan: "Kecap lemes tina 'dahar' nyaéta 'tuang'.",
  },
  {
    topik: "Undak Usuk Basa",
    soal: "Kecap hormat (lemes) tina 'nginum' nyaéta…",
    pilihan: ["ngaleueut", "nyatu", "kulem", "angkat"],
    jawaban: 0,
    catatan: "Kecap lemes tina 'nginum' nyaéta 'ngaleueut'.",
  },
  {
    topik: "Undak Usuk Basa",
    soal: "Kecap hormat (lemes) tina 'gering' (sakit) nyaéta…",
    pilihan: ["udur", "damang", "cageur", "bagja"],
    jawaban: 0,
    catatan: "Kecap lemes tina 'gering' nyaéta 'udur'. Damang/cageur = sehat.",
  },
  {
    topik: "Sasatoan",
    soal: "Sato anu sok luncat-luncatan jeung resep wortel nyaéta…",
    pilihan: ["kelenci (terwelu)", "embé", "hayam", "lauk"],
    jawaban: 0,
    catatan: "Kelenci (terwelu) resep dahar wortel sarta sok luncat-luncatan.",
  },
  {
    topik: "Dongéng",
    soal: "Carita sasakala (asal-usul) ngeunaan kajadian hiji tempat disebut…",
    pilihan: ["legénda (sasakala)", "fabel", "biografi", "iklan"],
    jawaban: 0,
    catatan: "Carita asal-usul tempat disebut legénda atawa sasakala.",
  },
  {
    topik: "Wilangan",
    soal: "Angka '20' dina basa Sunda nyaéta…",
    pilihan: ["dua puluh", "sapuluh", "salawe", "lima belas"],
    jawaban: 0,
    catatan: "20 = dua puluh; 10 = sapuluh; 25 = salawe.",
  },
  {
    topik: "Wilangan",
    soal: "'Salawe' dina basa Sunda hartina angka…",
    pilihan: ["25", "15", "20", "50"],
    jawaban: 0,
    catatan: "Salawe = 25.",
  },
  {
    topik: "Warna",
    soal: "Warna 'hideung' dina basa Indonésia hartina…",
    pilihan: ["hitam", "putih", "merah", "hijau"],
    jawaban: 0,
    catatan: "Hideung = hitam.",
  },
  {
    topik: "Warna",
    soal: "Warna 'konéng' dina basa Indonésia hartina…",
    pilihan: ["kuning", "hijau", "merah", "biru"],
    jawaban: 0,
    catatan: "Konéng = kuning.",
  },
  {
    topik: "Anggota Awak",
    soal: "'Tarang' dina basa Indonésia hartina…",
    pilihan: ["dahi", "hidung", "pipi", "telinga"],
    jawaban: 0,
    catatan: "Tarang = dahi.",
  },
  {
    topik: "Kosakata",
    soal: "'Cai' dina basa Indonésia hartina…",
    pilihan: ["air", "api", "tanah", "angin"],
    jawaban: 0,
    catatan: "Cai = air.",
  },
  {
    topik: "Kosakata",
    soal: "'Seuneu' dina basa Indonésia hartina…",
    pilihan: ["api", "air", "angin", "tanah"],
    jawaban: 0,
    catatan: "Seuneu = api.",
  },
  {
    topik: "Arah",
    soal: "'Kalér' dina basa Indonésia hartina arah…",
    pilihan: ["utara", "selatan", "timur", "barat"],
    jawaban: 0,
    catatan: "Kalér = utara; kidul = selatan; wétan = timur; kulon = barat.",
  },
  {
    topik: "Waktu",
    soal: "'Isukan' dina basa Indonésia hartina…",
    pilihan: ["besok", "kemarin", "sekarang", "nanti sore"],
    jawaban: 0,
    catatan: "Isukan = besok.",
  },
  {
    topik: "Hirup Séhat",
    soal: "Sangkan huntu teu garowong (bolong), urang ulah loba dahar nu…",
    pilihan: ["amis-amis (permén jeung coklat)", "sayur", "bungbuahan", "cai"],
    jawaban: 0,
    catatan: "Loba dahar nu amis bisa nyababkeun huntu garowong.",
  },
  {
    topik: "Gambar — Anak Sasatoan",
    gambar: "🐎",
    soal: "Anak sato dina gambar ieu (kuda) dina basa Sunda disebut…",
    pilihan: ["belo", "kirik", "meri", "ciak"],
    jawaban: 0,
    catatan: "Anak kuda = belo.",
  },
  {
    topik: "Gambar — Anak Sasatoan",
    gambar: "🦆",
    soal: "Anak sato dina gambar ieu (bébék) dina basa Sunda disebut…",
    pilihan: ["meri", "belo", "kirik", "ciak"],
    jawaban: 0,
    catatan: "Anak bébék = meri.",
  },
  {
    topik: "Gambar — Anak Sasatoan",
    gambar: "🐔",
    soal: "Anak sato dina gambar ieu (hayam) dina basa Sunda disebut…",
    pilihan: ["ciak", "meri", "belo", "kirik"],
    jawaban: 0,
    catatan: "Anak hayam = ciak.",
  },
  {
    topik: "Gambar — Anak Sasatoan",
    gambar: "🐶",
    soal: "Anak sato dina gambar ieu (anjing) dina basa Sunda disebut…",
    pilihan: ["kirik", "ciak", "meri", "belo"],
    jawaban: 0,
    catatan: "Anak anjing = kirik.",
  },
  {
    topik: "Gambar — Warna",
    gambar: "🟥",
    soal: "Warna dina gambar ieu, dina basa Sunda disebut…",
    pilihan: ["beureum", "héjo", "bodas", "hideung"],
    jawaban: 0,
    catatan: "Warna beureum = merah.",
  },
  {
    topik: "Gambar — Warna",
    gambar: "🟩",
    soal: "Warna dina gambar ieu, dina basa Sunda disebut…",
    pilihan: ["héjo", "beureum", "konéng", "bodas"],
    jawaban: 0,
    catatan: "Warna héjo = hijau.",
  },
  {
    topik: "Gambar — Tutuwuhan",
    gambar: "🥥",
    soal: "Buah dina gambar ieu, dina basa Sunda disebut…",
    pilihan: ["kalapa", "cau", "jeruk", "gedang"],
    jawaban: 0,
    catatan: "Buah dina gambar nyaéta kalapa (kelapa).",
  },
  {
    topik: "Gambar — Anggota Awak",
    gambar: "👂",
    soal: "Bagian awak dina gambar ieu, dina basa Sunda disebut…",
    pilihan: ["ceuli", "panon", "irung", "baham"],
    jawaban: 0,
    catatan: "Ceuli = telinga. (panon = mata, irung = hidung, baham = mulut)",
  },
  {
    topik: "Undak Usuk Basa",
    soal: "Kecap hormat (lemes) tina 'imah sorangan' nyaéta…",
    pilihan: ["rorompok", "bumi", "gedong", "saung"],
    jawaban: 0,
    catatan: "Imah sorangan = rorompok; imah batur = bumi.",
  },
  {
    topik: "Undak Usuk Basa",
    soal: "Kecap hormat (lemes) tina 'ngaran' (nama) nyaéta…",
    pilihan: ["jenengan", "landihan", "gelar", "sebutan"],
    jawaban: 0,
    catatan: "Kecap lemes tina 'ngaran' nyaéta 'jenengan' (atawa 'wasta').",
  },
  {
    topik: "Undak Usuk Basa",
    soal: "Kecap hormat (lemes) tina 'datang' nyaéta…",
    pilihan: ["sumping", "indit", "balik", "lumpat"],
    jawaban: 0,
    catatan: "Kecap lemes tina 'datang' nyaéta 'sumping'.",
  },
  {
    topik: "Undak Usuk Basa",
    soal: "Kecap hormat (lemes) tina 'ménta' (minta) nyaéta…",
    pilihan: ["nyuhunkeun", "ngarebut", "méré", "nyokot"],
    jawaban: 0,
    catatan: "Kecap lemes tina 'ménta' nyaéta 'nyuhunkeun'.",
  },
  {
    topik: "Undak Usuk Basa",
    soal: "Kecap hormat (lemes) tina 'méré' (memberi) nyaéta…",
    pilihan: ["maparin", "nyokot", "ménta", "nyimpen"],
    jawaban: 0,
    catatan: "Kecap lemes tina 'méré' nyaéta 'maparin' (atawa 'masihan').",
  },
  {
    topik: "Undak Usuk Basa",
    soal: "Kecap hormat (lemes) tina 'nyaho' (tahu) nyaéta…",
    pilihan: ["uninga", "hilap", "poho", "bingung"],
    jawaban: 0,
    catatan: "Kecap lemes tina 'nyaho' nyaéta 'uninga'.",
  },
  {
    topik: "Undak Usuk Basa",
    soal: "Kecap hormat (lemes) tina 'poho' (lupa) nyaéta…",
    pilihan: ["hilap", "émut", "apal", "nyaho"],
    jawaban: 0,
    catatan: "Poho = hilap; inget = émut.",
  },
  {
    topik: "Undak Usuk Basa",
    soal: "Kecap hormat (lemes) tina 'inget' (ingat) nyaéta…",
    pilihan: ["émut", "hilap", "poho", "bingung"],
    jawaban: 0,
    catatan: "Inget = émut; poho = hilap.",
  },
  {
    topik: "Babasan",
    soal: "Jalma anu 'hampang birit' hartina jalma anu…",
    pilihan: ["getol/gampang dititah", "kedul", "sombong", "bodo"],
    jawaban: 0,
    catatan: "'Hampang birit' = getol, gampang dititah (rajin).",
  },
  {
    topik: "Babasan",
    soal: "Jalma anu 'buntut kasiran' hartina jalma anu…",
    pilihan: ["medit (pelit)", "berehan", "soméah", "pinter"],
    jawaban: 0,
    catatan: "'Buntut kasiran' = medit/pelit (kikir).",
  },
  {
    topik: "Babasan",
    soal: "Jalma anu 'panjang leungeun' hartina jalma anu…",
    pilihan: ["resep maling (mencuri)", "bageur", "getol gawé", "berehan"],
    jawaban: 0,
    catatan: "'Panjang leungeun' = resep maling (suka mencuri).",
  },
  {
    topik: "Babasan",
    soal: "Jalma anu 'hampang leungeun' hartina jalma anu…",
    pilihan: ["resep neunggeulan (gampang memukul)", "bageur pisan", "berehan", "pinter"],
    jawaban: 0,
    catatan: "'Hampang leungeun' = resep neunggeulan (suka memukul).",
  },
  {
    topik: "Pupuh",
    soal: "Jumlah pupuh dina kasenian Sunda aya…",
    pilihan: ["17", "10", "20", "5"],
    jawaban: 0,
    catatan: "Pupuh aya 17 (Sékar Ageung jeung Sékar Alit).",
  },
  {
    topik: "Kasenian Sunda",
    soal: "Lagu daérah Sunda disebut ogé…",
    pilihan: ["kawih", "dangdut", "keroncong", "pop"],
    jawaban: 0,
    catatan: "Lagu Sunda disebut kawih.",
  },
  {
    topik: "Kasenian Sunda",
    soal: "Wayang golék téh dijieun tina bahan…",
    pilihan: ["kai (kayu)", "kulit", "beusi", "kaca"],
    jawaban: 0,
    catatan: "Wayang golék dijieun tina kai; wayang kulit tina kulit.",
  },
  {
    topik: "Kaulinan",
    soal: "Ieu di handap conto kaulinan barudak Sunda, nyaéta…",
    pilihan: ["ucing sumput", "balap motor", "nonton TV", "maén HP"],
    jawaban: 0,
    catatan: "Ucing sumput (petak umpet) mangrupa kaulinan barudak Sunda.",
  },
  {
    topik: "Dongéng",
    soal: "Tokoh dongéng Sunda anu kawéntar pinter, cerdik, sarta lucu nyaéta…",
    pilihan: ["Si Kabayan", "Sangkuriang", "Lutung Kasarung", "Mundinglaya"],
    jawaban: 0,
    catatan: "Si Kabayan kawéntar cerdik tur lucu.",
  },
  {
    topik: "Dongéng",
    soal: "Pamajikan (istri) Si Kabayan ngaranna…",
    pilihan: ["Nyi Iteung", "Dayang Sumbi", "Purbasari", "Mundinglaya"],
    jawaban: 0,
    catatan: "Pamajikan Si Kabayan nyaéta Nyi Iteung.",
  },
  {
    topik: "Dongéng",
    soal: "Dina dongéng Sangkuriang, indung Sangkuriang ngaranna…",
    pilihan: ["Dayang Sumbi", "Nyi Iteung", "Purbasari", "Nyi Pohaci"],
    jawaban: 0,
    catatan: "Indung Sangkuriang nyaéta Dayang Sumbi.",
  },
  {
    topik: "Dongéng",
    soal: "Dina dongéng Lutung Kasarung, putri bungsu anu hadé haténa ngaranna…",
    pilihan: ["Purbasari", "Purbararang", "Dayang Sumbi", "Nyi Iteung"],
    jawaban: 0,
    catatan: "Purbasari nyaéta putri bungsu nu hadé haté; Purbararang lanceuk nu jahat.",
  },
  {
    topik: "Aksara",
    soal: "Aksara asli Sunda disebut ogé aksara…",
    pilihan: ["Ngalagena (Kaganga)", "Latin", "Arab", "Jawa"],
    jawaban: 0,
    catatan: "Aksara Sunda disebut aksara Ngalagena atawa Kaganga.",
  },
  {
    topik: "Wilangan",
    soal: "Angka '100' dina basa Sunda nyaéta…",
    pilihan: ["saratus", "sarébu", "salawe", "dua puluh"],
    jawaban: 0,
    catatan: "100 = saratus; 1000 = sarébu.",
  },
  {
    topik: "Wilangan",
    soal: "Angka '1000' dina basa Sunda nyaéta…",
    pilihan: ["sarébu", "saratus", "salaksa", "salawe"],
    jawaban: 0,
    catatan: "1000 = sarébu.",
  },
  {
    topik: "Wilangan",
    soal: "Tilu ditambah dua hasilna…",
    pilihan: ["lima", "opat", "genep", "tujuh"],
    jawaban: 0,
    catatan: "3 + 2 = 5 (lima).",
  },
  {
    topik: "Wilangan",
    soal: "Genep dikurangan dua hasilna…",
    pilihan: ["opat", "lima", "tilu", "dua"],
    jawaban: 0,
    catatan: "6 − 2 = 4 (opat).",
  },
  {
    topik: "Arah",
    soal: "'Wétan' dina basa Indonésia hartina arah…",
    pilihan: ["timur", "barat", "utara", "selatan"],
    jawaban: 0,
    catatan: "Wétan = timur.",
  },
  {
    topik: "Arah",
    soal: "'Kulon' dina basa Indonésia hartina arah…",
    pilihan: ["barat", "timur", "utara", "selatan"],
    jawaban: 0,
    catatan: "Kulon = barat.",
  },
  {
    topik: "Arah",
    soal: "'Kidul' dina basa Indonésia hartina arah…",
    pilihan: ["selatan", "utara", "timur", "barat"],
    jawaban: 0,
    catatan: "Kidul = selatan; kalér = utara.",
  },
  {
    topik: "Kajadian Alam",
    soal: "Panonpoé surup (terbenam) di beulah…",
    pilihan: ["kulon (barat)", "wétan", "kalér", "kidul"],
    jawaban: 0,
    catatan: "Panonpoé surup di kulon (barat).",
  },
  {
    topik: "Kosakata",
    soal: "'Sasih' dina basa Indonésia hartina…",
    pilihan: ["bulan", "minggu", "tahun", "hari"],
    jawaban: 0,
    catatan: "Sasih = bulan (kalénder).",
  },
  {
    topik: "Kosakata",
    soal: "'Beurang' dina basa Indonésia hartina…",
    pilihan: ["siang", "malam", "pagi", "sore"],
    jawaban: 0,
    catatan: "Beurang = siang.",
  },
  {
    topik: "Kosakata",
    soal: "'Peuting' dina basa Indonésia hartina…",
    pilihan: ["malam", "siang", "pagi", "sore"],
    jawaban: 0,
    catatan: "Peuting = malam.",
  },
  {
    topik: "Kosakata",
    soal: "'Énjing' dina basa Indonésia hartina…",
    pilihan: ["pagi", "malam", "siang", "sore"],
    jawaban: 0,
    catatan: "Énjing = pagi.",
  },
  {
    topik: "Pagawéan",
    soal: "Jalma anu néwak lauk di laut disebut…",
    pilihan: ["nelayan", "patani", "dokter", "guru"],
    jawaban: 0,
    catatan: "Nu néwak lauk di laut nyaéta nelayan.",
  },
  {
    topik: "Pagawéan",
    soal: "Jalma anu ngajaga kaamanan kampung (ronda) disebut…",
    pilihan: ["hansip", "patani", "nelayan", "guru"],
    jawaban: 0,
    catatan: "Nu ngajaga kaamanan kampung nyaéta hansip.",
  },
];

export function getSoal(kelas) {
  return kelas === 3 ? SOAL_KELAS3 : SOAL_KELAS2;
}
